dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}